### ISSUE TITLE
AttributeError: 'zlib._ZlibDecompressor' object has no attribute 'unconsumed_tail'

### ISSUE THREAD

**Issue by ericleasemorgan** [harvard-lil/warcbench#45]
I used the following command to create a warc file with wget (I think):

  wget --warc-file=homer --warc-max-size=1000M --warc-cdx -r -np -nH http://carrels.distantreader.org/author-homer-gutenberg/index.htm

This resulted in the creation of three files:

  1. homer-00000.warc.gz
  2. homer-meta.warc.gz
  3. homer.cdx
  
I ran the following commands against the first two files:

  wb summarize homer-00000.warc.gz
  wb summarize homer-meta.warc.gz

And I get the following error:

  AttributeError: 'zlib._ZlibDecompressor' object has no attribute 'unconsumed_tail'

Alas, what am I doing wrong? Did I not create a warc file to begin with? Do I need to update a library someplace?

**Comment by rebeccacremona** [comment]
Hi @ericleasemorgan! 

What version of python are you running? 

As far as I know, CPython has supported `Decompress.unconsumed_tail` since Python 3.3; we have not tested WARCbench extensively with older versions of python, but I think it should work with anything 3.10 or up (https://github.com/harvard-lil/warcbench/blob/main/pyproject.toml#L9, https://github.com/harvard-lil/warcbench/blob/main/.python-version, https://github.com/harvard-lil/warcbench/blob/main/.github/workflows/test.yaml#L13) 

Cheers,

**Comment by ericleasemorgan** [comment]
Resolved. I need to first uncompress the warc.gz file and then use something like workbench. Duh!

**Comment by rebeccacremona** [comment]
(Glad to hear that worked! You should be able to work directly with the `.gz` files without decompressing them too, though, so if you'd like to troubleshoot that further, just let us know. My suspicion is, again, python version mismatch.)

**Comment by ericleasemorgan** [comment]
I am using Python version 3.12:

Python 3.12.7 | packaged by Anaconda, Inc. | (main, Oct  4 2024, 08:22:19) [Clang 14.0.6 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
